version: '3.8'

services:
  # MinIO service for object storage during development/testing
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "${MINIO_API_PORT:-9000}:9000"      # MinIO API
      - "${MINIO_CONSOLE_PORT:-9001}:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: ${HA_AWS_ACCESS_KEY:-naeva_minio}
      MINIO_ROOT_PASSWORD: ${HA_AWS_SECRET_KEY:-N43v4t3c_M1n10}
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio/data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ov-ha-recorder

  # MinIO Client for bucket creation and management
  minio-mc:
    image: minio/mc:latest
    container_name: minio-mc
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${HA_AWS_ACCESS_KEY:-naeva_minio}
      MINIO_ROOT_PASSWORD: ${HA_AWS_SECRET_KEY:-N43v4t3c_M1n10}
      MINIO_BUCKET_NAME: ${HA_AWS_S3_BUCKET:-ov-recordings}
    entrypoint: >
      /bin/sh -c "
      echo 'Setting up MinIO...';
      echo 'Using credentials: $$MINIO_ROOT_USER / [password hidden]';
      echo 'Creating bucket: $$MINIO_BUCKET_NAME';
      /usr/bin/mc alias set local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
      /usr/bin/mc mb local/$$MINIO_BUCKET_NAME --ignore-existing;
      /usr/bin/mc policy set public local/$$MINIO_BUCKET_NAME;
      echo 'MinIO setup completed successfully';
      "
    networks:
      - ov-ha-recorder

  # Your custom OpenVidu recording image
  openvidu-recording:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TAG=${TAG:-latest}
    image: openvidu/openvidu-recording:${TAG:-latest}
    container_name: openvidu-recording-${TAG:-latest}
    depends_on:
      - minio-mc
    environment:
      # MinIO connection settings (using your HA variable names)
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=${HA_AWS_ACCESS_KEY:-naeva_minio}
      - MINIO_SECRET_KEY=${HA_AWS_SECRET_KEY:-N43v4t3c_M1n10}
      - MINIO_BUCKET=${HA_AWS_S3_BUCKET:-ov-recordings}
      # HA Recorder specific variables
      - HA_AWS_S3_SERVICE_ENDPOINT=${HA_AWS_S3_SERVICE_ENDPOINT}
      - HA_AWS_S3_BUCKET=${HA_AWS_S3_BUCKET:-ov-recordings}
      - HA_AWS_ACCESS_KEY=${HA_AWS_ACCESS_KEY:-naeva_minio}
      - HA_AWS_SECRET_KEY=${HA_AWS_SECRET_KEY:-N43v4t3c_M1n10}
      - MINIO_API_PORT=${MINIO_API_PORT:-9000}
      - HA_RECORDING_STORAGE=${HA_RECORDING_STORAGE:-local}
      - CHUNK_FOLDER=${CHUNK_FOLDER:-/local-chunks}
      - CHUNK_TIME_SIZE=${CHUNK_TIME_SIZE:-20}
      # Recording settings
      - RECORDING_PATH=/recordings
    volumes:
      - ./data/recorder/data:/recordings
      # Mount your scripts and utils if they're in separate directories
      - ./scripts:/scripts:ro
      - ./utils:/utils:ro
    networks:
      - ov-ha-recorder
    # Use profiles to control when recorder starts
    profiles:
      - recorder
      - test

volumes:
  # Keep named volume as fallback for other configurations
  minio_data:
    driver: local
  recordings_data:
    driver: local

networks:
  ov-ha-recorder:
    driver: bridge